In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
# Let's one hot encode our dataset
insurance_one_hot_encode = pd.get_dummies(insurance)
insurance_one_hot_encode.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,0,1,1,0,0,1,0,0
4,32,28.880,0,3866.85520,0,1,1,0,0,1,0,0

In [6]:
# Let's create features and labels
X = insurance_one_hot_encode.drop("charges", axis= 1)
X.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,1,0,0,1,0,0,0,1
1,18,33.770,1,0,1,1,0,0,0,1,0
2,28,33.000,3,0,1,1,0,0,0,1,0
3,33,22.705,0,0,1,1,0,0,1,0,0
4,32,28.880,0,0,1,1,0,0,1,0,0

In [7]:
y = insurance_one_hot_encode["charges"]
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [8]:
len(X), len(y)

(1338, 1338)

In [9]:
# Lets Split our data in training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Last model didn't provide great results. So lets improve our model

In [12]:
# Lets build a model with 3 layers, 100 epochs and Adam optimizer

# Set random seed
tf.random.set_seed(42)

# 1. Create a model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1),
    tf.keras.layers.Dense(1),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['mae'])

# 3. Fit the model
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
34/34 [==============================] - 1s 2ms/step - loss: 13346.8604 - mae: 13346.8604
Epoch 2/100
34/34 [==============================] - 0s 2ms/step - loss: 13346.0908 - mae: 13346.0908
Epoch 3/100
34/34 [==============================] - 0s 2ms/step - loss: 13345.3818 - mae: 13345.3818
Epoch 4/100
34/34 [==============================] - 0s 2ms/step - loss: 13344.3975 - mae: 13344.3975
Epoch 5/100
34/34 [==============================] - 0s 2ms/step - loss: 13342.8262 - mae: 13342.8262
Epoch 6/100
34/34 [==============================] - 0s 2ms/step - loss: 13340.4463 - mae: 13340.4463
Epoch 7/100
34/34 [==============================] - 0s 2ms/step - loss: 13337.0977 - mae: 13337.0977
Epoch 8/100
34/34 [==============================] - 0s 2ms/step - loss: 13332.6221 - mae: 13332.6221
Epoch 9/100
34/34 [==============================] - 0s 2ms/step - loss: 13326.8555 - mae: 13326.8555
Epoch 10/100
34/34 [==============================] - 0s 2ms/step - loss: 13319.6836 - mae: 13319.6836
Epoch 11/100
34/34 [==============================] - 0s 2ms/step - loss: 13310.9561 - mae: 13310.9561
Epoch 12/100
34/34 [==============================] - 0s 3ms/step - loss: 13300.5449 - mae: 13300.5449
Epoch 13/100
34/34 [==============================] - 0s 2ms/step - loss: 13288.3779 - mae: 13288.3779
Epoch 14/100
34/34 [==============================] - 0s 2ms/step - loss: 13274.2793 - mae: 13274.2793
Epoch 15/100
34/34 [==============================] - 0s 2ms/step - loss: 13258.1973 - mae: 13258.1973
Epoch 16/100
34/34 [==============================] - 0s 2ms/step - loss: 13239.9248 - mae: 13239.9248
Epoch 17/100
34/34 [==============================] - 0s 2ms/step - loss: 13219.4609 - mae: 13219.4609
Epoch 18/100
34/34 [==============================] - 0s 2ms/step - loss: 13196.6260 - mae: 13196.6260
Epoch 19/100
34/34 [==============================] - 0s 2ms/step - loss: 13171.3340 - mae: 13171.3340
Epoch 20/100
34/34 [==============================] - 0s 2ms/step - loss: 13143.5527 - mae: 13143.5527
Epoch 21/100
34/34 [==============================] - 0s 2ms/step - loss: 13113.1631 - mae: 13113.1631
Epoch 22/100
34/34 [==============================] - 0s 2ms/step - loss: 13080.0977 - mae: 13080.0977
Epoch 23/100
34/34 [==============================] - 0s 2ms/step - loss: 13044.2607 - mae: 13044.2607
Epoch 24/100
34/34 [==============================] - 0s 2ms/step - loss: 13005.4873 - mae: 13005.4873
Epoch 25/100
34/34 [==============================] - 0s 2ms/step - loss: 12963.8496 - mae: 12963.8496
Epoch 26/100
34/34 [==============================] - 0s 2ms/step - loss: 12919.0312 - mae: 12919.0312
Epoch 27/100
34/34 [==============================] - 0s 2ms/step - loss: 12871.2178 - mae: 12871.2178
Epoch 28/100
34/34 [==============================] - 0s 2ms/step - loss: 12820.2598 - mae: 12820.2598
Epoch 29/100
34/34 [==============================] - 0s 2ms/step - loss: 12766.0244 - mae: 12766.0244
Epoch 30/100
34/34 [==============================] - 0s 2ms/step - loss: 12708.5352 - mae: 12708.5352
Epoch 31/100
34/34 [==============================] - 0s 2ms/step - loss: 12647.6016 - mae: 12647.6016
Epoch 32/100
34/34 [==============================] - 0s 2ms/step - loss: 12583.2715 - mae: 12583.2715
Epoch 33/100
34/34 [==============================] - 0s 2ms/step - loss: 12515.3184 - mae: 12515.3184
Epoch 34/100
34/34 [==============================] - 0s 2ms/step - loss: 12444.2129 - mae: 12444.2129
Epoch 35/100
34/34 [==============================] - 0s 2ms/step - loss: 12369.1904 - mae: 12369.1904
Epoch 36/100
34/34 [==============================] - 0s 2ms/step - loss: 12290.7012 - mae: 12290.7012
Epoch 37/100
34/34 [==============================] - 0s 2ms/step - loss: 12208.5098 - mae: 12208.5098
Epoch 38/100
34/34 [==============================] - 0s 2ms/step - loss: 12122.6611 - mae: 12122.6611
Epoch 39/100
34/34 [==============================] - 0s 2ms/step - loss: 12033.0117 - mae: 12033.0117
Epoch 40/100
34/34 [==============================] - 0s 2ms/step - loss: 11939.8340 - mae: 11939.8340
Epoch 41/100
34/34 [==============================] - 0s 2ms/step - loss: 11843.1211 - mae: 11843.1211
Epoch 42/100
34/34 [==============================] - 0s 2ms/step - loss: 11742.9678 - mae: 11742.9678
Epoch 43/100
34/34 [==============================] - 0s 2ms/step - loss: 11640.0010 - mae: 11640.0010
Epoch 44/100
34/34 [==============================] - 0s 2ms/step - loss: 11533.1631 - mae: 11533.1631
Epoch 45/100
34/34 [==============================] - 0s 2ms/step - loss: 11423.4229 - mae: 11423.4229
Epoch 46/100
34/34 [==============================] - 0s 2ms/step - loss: 11310.1738 - mae: 11310.1738
Epoch 47/100
34/34 [==============================] - 0s 2ms/step - loss: 11195.3730 - mae: 11195.3730
Epoch 48/100
34/34 [==============================] - 0s 2ms/step - loss: 11077.4248 - mae: 11077.4248
Epoch 49/100
34/34 [==============================] - 0s 2ms/step - loss: 10958.6465 - mae: 10958.6465
Epoch 50/100
34/34 [==============================] - 0s 2ms/step - loss: 10838.6094 - mae: 10838.6094
Epoch 51/100
34/34 [==============================] - 0s 2ms/step - loss: 10717.6514 - mae: 10717.6514
Epoch 52/100
34/34 [==============================] - 0s 2ms/step - loss: 10596.2852 - mae: 10596.2852
Epoch 53/100
34/34 [==============================] - 0s 2ms/step - loss: 10475.8438 - mae: 10475.8438
Epoch 54/100
34/34 [==============================] - 0s 2ms/step - loss: 10356.2383 - mae: 10356.2383
Epoch 55/100
34/34 [==============================] - 0s 2ms/step - loss: 10237.5586 - mae: 10237.5586
Epoch 56/100
34/34 [==============================] - 0s 2ms/step - loss: 10117.2803 - mae: 10117.2803
Epoch 57/100
34/34 [==============================] - 0s 2ms/step - loss: 9996.7676 - mae: 9996.7676
Epoch 58/100
34/34 [==============================] - 0s 2ms/step - loss: 9877.4375 - mae: 9877.4375
Epoch 59/100
34/34 [==============================] - 0s 2ms/step - loss: 9759.1914 - mae: 9759.1914
Epoch 60/100
34/34 [==============================] - 0s 2ms/step - loss: 9642.1758 - mae: 9642.1758
Epoch 61/100
34/34 [==============================] - 0s 2ms/step - loss: 9522.6611 - mae: 9522.6611
Epoch 62/100
34/34 [==============================] - 0s 2ms/step - loss: 9405.3594 - mae: 9405.3594
Epoch 63/100
34/34 [==============================] - 0s 2ms/step - loss: 9289.2627 - mae: 9289.2627
Epoch 64/100
34/34 [==============================] - 0s 2ms/step - loss: 9172.5020 - mae: 9172.5020
Epoch 65/100
34/34 [==============================] - 0s 2ms/step - loss: 9059.2500 - mae: 9059.2500
Epoch 66/100
34/34 [==============================] - 0s 2ms/step - loss: 8949.3799 - mae: 8949.3799
Epoch 67/100
34/34 [==============================] - 0s 2ms/step - loss: 8842.8330 - mae: 8842.8330
Epoch 68/100
34/34 [==============================] - 0s 2ms/step - loss: 8740.3047 - mae: 8740.3047
Epoch 69/100
34/34 [==============================] - 0s 2ms/step - loss: 8640.9688 - mae: 8640.9688
Epoch 70/100
34/34 [==============================] - 0s 3ms/step - loss: 8543.3203 - mae: 8543.3203
Epoch 71/100
34/34 [==============================] - 0s 3ms/step - loss: 8449.6084 - mae: 8449.6084
Epoch 72/100
34/34 [==============================] - 0s 3ms/step - loss: 8358.4551 - mae: 8358.4551
Epoch 73/100
34/34 [==============================] - 0s 3ms/step - loss: 8271.7402 - mae: 8271.7402
Epoch 74/100
34/34 [==============================] - 0s 3ms/step - loss: 8189.2769 - mae: 8189.2769
Epoch 75/100
34/34 [==============================] - 0s 3ms/step - loss: 8115.2710 - mae: 8115.2710
Epoch 76/100
34/34 [==============================] - 0s 2ms/step - loss: 8042.3970 - mae: 8042.3970
Epoch 77/100
34/34 [==============================] - 0s 3ms/step - loss: 7974.0029 - mae: 7974.0029
Epoch 78/100
34/34 [==============================] - 0s 3ms/step - loss: 7910.9438 - mae: 7910.9438
Epoch 79/100
34/34 [==============================] - 0s 3ms/step - loss: 7853.4878 - mae: 7853.4878
Epoch 80/100
34/34 [==============================] - 0s 3ms/step - loss: 7800.3496 - mae: 7800.3496
Epoch 81/100
34/34 [==============================] - 0s 3ms/step - loss: 7754.0073 - mae: 7754.0073
Epoch 82/100
34/34 [==============================] - 0s 3ms/step - loss: 7712.8750 - mae: 7712.8750
Epoch 83/100
34/34 [==============================] - 0s 3ms/step - loss: 7673.4595 - mae: 7673.4595
Epoch 84/100
34/34 [==============================] - 0s 3ms/step - loss: 7641.0610 - mae: 7641.0610
Epoch 85/100
34/34 [==============================] - 0s 3ms/step - loss: 7611.5410 - mae: 7611.5410
Epoch 86/100
34/34 [==============================] - 0s 3ms/step - loss: 7587.3921 - mae: 7587.3921
Epoch 87/100
34/34 [==============================] - 0s 3ms/step - loss: 7566.5117 - mae: 7566.5117
Epoch 88/100
34/34 [==============================] - 0s 3ms/step - loss: 7547.9624 - mae: 7547.9624
Epoch 89/100
34/34 [==============================] - 0s 3ms/step - loss: 7531.9463 - mae: 7531.9463
Epoch 90/100
34/34 [==============================] - 0s 3ms/step - loss: 7518.3442 - mae: 7518.3442
Epoch 91/100
34/34 [==============================] - 0s 3ms/step - loss: 7505.7876 - mae: 7505.7876
Epoch 92/100
34/34 [==============================] - 0s 3ms/step - loss: 7495.7607 - mae: 7495.7607
Epoch 93/100
34/34 [==============================] - 0s 3ms/step - loss: 7487.0234 - mae: 7487.0234
Epoch 94/100
34/34 [==============================] - 0s 3ms/step - loss: 7480.1353 - mae: 7480.1353
Epoch 95/100
34/34 [==============================] - 0s 3ms/step - loss: 7473.8672 - mae: 7473.8672
Epoch 96/100
34/34 [==============================] - 0s 3ms/step - loss: 7467.6792 - mae: 7467.6792
Epoch 97/100
34/34 [==============================] - 0s 3ms/step - loss: 7462.9805 - mae: 7462.9805
Epoch 98/100
34/34 [==============================] - 0s 3ms/step - loss: 7457.8135 - mae: 7457.8135
Epoch 99/100
34/34 [==============================] - 0s 2ms/step - loss: 7453.4043 - mae: 7453.4043
Epoch 100/100
34/34 [==============================] - 0s 2ms/step - loss: 7449.2036 - mae: 7449.2036

In [13]:
# Evaluate our model
model.evaluate(X_test,y_test)

9/9 [==============================] - 0s 2ms/step - loss: 7593.5791 - mae: 7593.5791

[7593.5791015625, 7593.5791015625]