In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
# Let's one hot encode our dataset
insurance_one_hot_encode = pd.get_dummies(insurance)
insurance_one_hot_encode.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,0,1,1,0,0,1,0,0
4,32,28.880,0,3866.85520,0,1,1,0,0,1,0,0

In [4]:
# let's create features and labels
X = insurance_one_hot_encode.drop("charges", axis= 1)
X.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,1,0,0,1,0,0,0,1
1,18,33.770,1,0,1,1,0,0,0,1,0
2,28,33.000,3,0,1,1,0,0,0,1,0
3,33,22.705,0,0,1,1,0,0,1,0,0
4,32,28.880,0,0,1,1,0,0,1,0,0

In [5]:
y = insurance_one_hot_encode["charges"]
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [6]:
# Lets divide our dataset into training data and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
560,46,19.950,2,1,0,1,0,0,1,0,0
1285,47,24.320,0,1,0,1,0,1,0,0,0
1142,52,24.860,0,1,0,1,0,0,0,1,0
969,39,34.320,5,1,0,1,0,0,0,1,0
486,54,21.470,3,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1095,18,31.350,4,1,0,1,0,1,0,0,0
1130,39,23.870,5,1,0,1,0,0,0,1,0
1294,58,25.175,0,0,1,1,0,1,0,0,0
860,37,47.600,2,1,0,0,1,0,0,0,1
1126,55,29.900,0,0,1,1,0,0,0,0,1

In [7]:
len(X_test)

268

In [8]:
len(X)

1338

In [9]:
0.2*1338

267.6

Again in last model we saw that our model is not performing that well. So we need to improve our model

In [10]:
# Build a model with 3 layers, 200 epochs and Adam optimizer

# Set random seed
tf.random.set_seed(42)

# 1. Create a model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['mae'])

# 3. Fit the model
model.fit(X_train, y_train, epochs=200)

Epoch 1/200
34/34 [==============================] - 1s 2ms/step - loss: 13310.0928 - mae: 13310.0928
Epoch 2/200
34/34 [==============================] - 0s 2ms/step - loss: 13266.7451 - mae: 13266.7451
Epoch 3/200
34/34 [==============================] - 0s 2ms/step - loss: 13203.3613 - mae: 13203.3613
Epoch 4/200
34/34 [==============================] - 0s 2ms/step - loss: 13107.6709 - mae: 13107.6709
Epoch 5/200
34/34 [==============================] - 0s 2ms/step - loss: 12965.2354 - mae: 12965.2354
Epoch 6/200
34/34 [==============================] - 0s 2ms/step - loss: 12758.8955 - mae: 12758.8955
Epoch 7/200
34/34 [==============================] - 0s 2ms/step - loss: 12472.7061 - mae: 12472.7061
Epoch 8/200
34/34 [==============================] - 0s 2ms/step - loss: 12091.2285 - mae: 12091.2285
Epoch 9/200
34/34 [==============================] - 0s 2ms/step - loss: 11603.4023 - mae: 11603.4023
Epoch 10/200
34/34 [==============================] - 0s 2ms/step - loss: 11016.8535 - mae: 11016.8535
Epoch 11/200
34/34 [==============================] - 0s 2ms/step - loss: 10374.1992 - mae: 10374.1992
Epoch 12/200
34/34 [==============================] - 0s 2ms/step - loss: 9711.8467 - mae: 9711.8467
Epoch 13/200
34/34 [==============================] - 0s 2ms/step - loss: 9063.2959 - mae: 9063.2959
Epoch 14/200
34/34 [==============================] - 0s 2ms/step - loss: 8476.7207 - mae: 8476.7207
Epoch 15/200
34/34 [==============================] - 0s 2ms/step - loss: 8024.1235 - mae: 8024.1235
Epoch 16/200
34/34 [==============================] - 0s 2ms/step - loss: 7713.5732 - mae: 7713.5732
Epoch 17/200
34/34 [==============================] - 0s 2ms/step - loss: 7565.9243 - mae: 7565.9243
Epoch 18/200
34/34 [==============================] - 0s 2ms/step - loss: 7501.9321 - mae: 7501.9321
Epoch 19/200
34/34 [==============================] - 0s 2ms/step - loss: 7472.3232 - mae: 7472.3232
Epoch 20/200
34/34 [==============================] - 0s 2ms/step - loss: 7457.0000 - mae: 7457.0000
Epoch 21/200
34/34 [==============================] - 0s 2ms/step - loss: 7448.8662 - mae: 7448.8662
Epoch 22/200
34/34 [==============================] - 0s 2ms/step - loss: 7439.0908 - mae: 7439.0908
Epoch 23/200
34/34 [==============================] - 0s 2ms/step - loss: 7431.4639 - mae: 7431.4639
Epoch 24/200
34/34 [==============================] - 0s 2ms/step - loss: 7423.5615 - mae: 7423.5615
Epoch 25/200
34/34 [==============================] - 0s 2ms/step - loss: 7419.6938 - mae: 7419.6938
Epoch 26/200
34/34 [==============================] - 0s 2ms/step - loss: 7407.0918 - mae: 7407.0918
Epoch 27/200
34/34 [==============================] - 0s 2ms/step - loss: 7398.4390 - mae: 7398.4390
Epoch 28/200
34/34 [==============================] - 0s 2ms/step - loss: 7390.1235 - mae: 7390.1235
Epoch 29/200
34/34 [==============================] - 0s 2ms/step - loss: 7382.3633 - mae: 7382.3633
Epoch 30/200
34/34 [==============================] - 0s 2ms/step - loss: 7373.8315 - mae: 7373.8315
Epoch 31/200
34/34 [==============================] - 0s 2ms/step - loss: 7365.4385 - mae: 7365.4385
Epoch 32/200
34/34 [==============================] - 0s 3ms/step - loss: 7358.2041 - mae: 7358.2041
Epoch 33/200
34/34 [==============================] - 0s 2ms/step - loss: 7348.9028 - mae: 7348.9028
Epoch 34/200
34/34 [==============================] - 0s 2ms/step - loss: 7339.9253 - mae: 7339.9253
Epoch 35/200
34/34 [==============================] - 0s 2ms/step - loss: 7331.2949 - mae: 7331.2949
Epoch 36/200
34/34 [==============================] - 0s 2ms/step - loss: 7322.1650 - mae: 7322.1650
Epoch 37/200
34/34 [==============================] - 0s 2ms/step - loss: 7313.0342 - mae: 7313.0342
Epoch 38/200
34/34 [==============================] - 0s 2ms/step - loss: 7305.6011 - mae: 7305.6011
Epoch 39/200
34/34 [==============================] - 0s 2ms/step - loss: 7295.1362 - mae: 7295.1362
Epoch 40/200
34/34 [==============================] - 0s 2ms/step - loss: 7286.5654 - mae: 7286.5654
Epoch 41/200
34/34 [==============================] - 0s 2ms/step - loss: 7277.4507 - mae: 7277.4507
Epoch 42/200
34/34 [==============================] - 0s 2ms/step - loss: 7270.8979 - mae: 7270.8979
Epoch 43/200
34/34 [==============================] - 0s 2ms/step - loss: 7259.7222 - mae: 7259.7222
Epoch 44/200
34/34 [==============================] - 0s 2ms/step - loss: 7250.3330 - mae: 7250.3330
Epoch 45/200
34/34 [==============================] - 0s 2ms/step - loss: 7241.1040 - mae: 7241.1040
Epoch 46/200
34/34 [==============================] - 0s 2ms/step - loss: 7232.4253 - mae: 7232.4253
Epoch 47/200
34/34 [==============================] - 0s 2ms/step - loss: 7225.1895 - mae: 7225.1895
Epoch 48/200
34/34 [==============================] - 0s 2ms/step - loss: 7212.7476 - mae: 7212.7476
Epoch 49/200
34/34 [==============================] - 0s 2ms/step - loss: 7205.5337 - mae: 7205.5337
Epoch 50/200
34/34 [==============================] - 0s 2ms/step - loss: 7192.5669 - mae: 7192.5669
Epoch 51/200
34/34 [==============================] - 0s 2ms/step - loss: 7185.2358 - mae: 7185.2358
Epoch 52/200
34/34 [==============================] - 0s 2ms/step - loss: 7174.1973 - mae: 7174.1973
Epoch 53/200
34/34 [==============================] - 0s 2ms/step - loss: 7163.6514 - mae: 7163.6514
Epoch 54/200
34/34 [==============================] - 0s 2ms/step - loss: 7152.8760 - mae: 7152.8760
Epoch 55/200
34/34 [==============================] - 0s 2ms/step - loss: 7142.7070 - mae: 7142.7070
Epoch 56/200
34/34 [==============================] - 0s 2ms/step - loss: 7132.1030 - mae: 7132.1030
Epoch 57/200
34/34 [==============================] - 0s 2ms/step - loss: 7121.8164 - mae: 7121.8164
Epoch 58/200
34/34 [==============================] - 0s 2ms/step - loss: 7110.9248 - mae: 7110.9248
Epoch 59/200
34/34 [==============================] - 0s 2ms/step - loss: 7102.2012 - mae: 7102.2012
Epoch 60/200
34/34 [==============================] - 0s 2ms/step - loss: 7090.0264 - mae: 7090.0264
Epoch 61/200
34/34 [==============================] - 0s 2ms/step - loss: 7079.2812 - mae: 7079.2812
Epoch 62/200
34/34 [==============================] - 0s 2ms/step - loss: 7067.6812 - mae: 7067.6812
Epoch 63/200
34/34 [==============================] - 0s 2ms/step - loss: 7057.0801 - mae: 7057.0801
Epoch 64/200
34/34 [==============================] - 0s 2ms/step - loss: 7046.3896 - mae: 7046.3896
Epoch 65/200
34/34 [==============================] - 0s 2ms/step - loss: 7035.5942 - mae: 7035.5942
Epoch 66/200
34/34 [==============================] - 0s 2ms/step - loss: 7023.4106 - mae: 7023.4106
Epoch 67/200
34/34 [==============================] - 0s 2ms/step - loss: 7013.5293 - mae: 7013.5293
Epoch 68/200
34/34 [==============================] - 0s 2ms/step - loss: 7001.3662 - mae: 7001.3662
Epoch 69/200
34/34 [==============================] - 0s 2ms/step - loss: 6989.2861 - mae: 6989.2861
Epoch 70/200
34/34 [==============================] - 0s 2ms/step - loss: 6978.1851 - mae: 6978.1851
Epoch 71/200
34/34 [==============================] - 0s 2ms/step - loss: 6965.8984 - mae: 6965.8984
Epoch 72/200
34/34 [==============================] - 0s 2ms/step - loss: 6954.4097 - mae: 6954.4097
Epoch 73/200
34/34 [==============================] - 0s 2ms/step - loss: 6941.4956 - mae: 6941.4956
Epoch 74/200
34/34 [==============================] - 0s 2ms/step - loss: 6929.1650 - mae: 6929.1650
Epoch 75/200
34/34 [==============================] - 0s 2ms/step - loss: 6916.1982 - mae: 6916.1982
Epoch 76/200
34/34 [==============================] - 0s 2ms/step - loss: 6905.0273 - mae: 6905.0273
Epoch 77/200
34/34 [==============================] - 0s 2ms/step - loss: 6890.7241 - mae: 6890.7241
Epoch 78/200
34/34 [==============================] - 0s 2ms/step - loss: 6879.1836 - mae: 6879.1836
Epoch 79/200
34/34 [==============================] - 0s 2ms/step - loss: 6865.3091 - mae: 6865.3091
Epoch 80/200
34/34 [==============================] - 0s 2ms/step - loss: 6852.5742 - mae: 6852.5742
Epoch 81/200
34/34 [==============================] - 0s 2ms/step - loss: 6839.3398 - mae: 6839.3398
Epoch 82/200
34/34 [==============================] - 0s 2ms/step - loss: 6829.6489 - mae: 6829.6489
Epoch 83/200
34/34 [==============================] - 0s 2ms/step - loss: 6815.7192 - mae: 6815.7192
Epoch 84/200
34/34 [==============================] - 0s 2ms/step - loss: 6799.3359 - mae: 6799.3359
Epoch 85/200
34/34 [==============================] - 0s 2ms/step - loss: 6787.1289 - mae: 6787.1289
Epoch 86/200
34/34 [==============================] - 0s 2ms/step - loss: 6771.8999 - mae: 6771.8999
Epoch 87/200
34/34 [==============================] - 0s 2ms/step - loss: 6758.1567 - mae: 6758.1567
Epoch 88/200
34/34 [==============================] - 0s 2ms/step - loss: 6742.7451 - mae: 6742.7451
Epoch 89/200
34/34 [==============================] - 0s 2ms/step - loss: 6727.3926 - mae: 6727.3926
Epoch 90/200
34/34 [==============================] - 0s 2ms/step - loss: 6713.0264 - mae: 6713.0264
Epoch 91/200
34/34 [==============================] - 0s 2ms/step - loss: 6697.5625 - mae: 6697.5625
Epoch 92/200
34/34 [==============================] - 0s 2ms/step - loss: 6684.0947 - mae: 6684.0947
Epoch 93/200
34/34 [==============================] - 0s 2ms/step - loss: 6669.1987 - mae: 6669.1987
Epoch 94/200
34/34 [==============================] - 0s 2ms/step - loss: 6654.9443 - mae: 6654.9443
Epoch 95/200
34/34 [==============================] - 0s 2ms/step - loss: 6639.0283 - mae: 6639.0283
Epoch 96/200
34/34 [==============================] - 0s 2ms/step - loss: 6624.4468 - mae: 6624.4468
Epoch 97/200
34/34 [==============================] - 0s 2ms/step - loss: 6610.7715 - mae: 6610.7715
Epoch 98/200
34/34 [==============================] - 0s 2ms/step - loss: 6594.5132 - mae: 6594.5132
Epoch 99/200
34/34 [==============================] - 0s 2ms/step - loss: 6581.0874 - mae: 6581.0874
Epoch 100/200
34/34 [==============================] - 0s 2ms/step - loss: 6567.4385 - mae: 6567.4385
Epoch 101/200
34/34 [==============================] - 0s 2ms/step - loss: 6554.6812 - mae: 6554.6812
Epoch 102/200
34/34 [==============================] - 0s 2ms/step - loss: 6542.4404 - mae: 6542.4404
Epoch 103/200
34/34 [==============================] - 0s 2ms/step - loss: 6530.7832 - mae: 6530.7832
Epoch 104/200
34/34 [==============================] - 0s 2ms/step - loss: 6520.1250 - mae: 6520.1250
Epoch 105/200
34/34 [==============================] - 0s 2ms/step - loss: 6509.8867 - mae: 6509.8867
Epoch 106/200
34/34 [==============================] - 0s 2ms/step - loss: 6500.1274 - mae: 6500.1274
Epoch 107/200
34/34 [==============================] - 0s 2ms/step - loss: 6492.4443 - mae: 6492.4443
Epoch 108/200
34/34 [==============================] - 0s 2ms/step - loss: 6486.2168 - mae: 6486.2168
Epoch 109/200
34/34 [==============================] - 0s 3ms/step - loss: 6478.2256 - mae: 6478.2256
Epoch 110/200
34/34 [==============================] - 0s 2ms/step - loss: 6472.1616 - mae: 6472.1616
Epoch 111/200
34/34 [==============================] - 0s 3ms/step - loss: 6464.8789 - mae: 6464.8789
Epoch 112/200
34/34 [==============================] - 0s 3ms/step - loss: 6456.7998 - mae: 6456.7998
Epoch 113/200
34/34 [==============================] - 0s 3ms/step - loss: 6451.2852 - mae: 6451.2852
Epoch 114/200
34/34 [==============================] - 0s 2ms/step - loss: 6445.1621 - mae: 6445.1621
Epoch 115/200
34/34 [==============================] - 0s 3ms/step - loss: 6438.9819 - mae: 6438.9819
Epoch 116/200
34/34 [==============================] - 0s 3ms/step - loss: 6435.3262 - mae: 6435.3262
Epoch 117/200
34/34 [==============================] - 0s 3ms/step - loss: 6427.7446 - mae: 6427.7446
Epoch 118/200
34/34 [==============================] - 0s 3ms/step - loss: 6422.3770 - mae: 6422.3770
Epoch 119/200
34/34 [==============================] - 0s 3ms/step - loss: 6418.7520 - mae: 6418.7520
Epoch 120/200
34/34 [==============================] - 0s 3ms/step - loss: 6411.3306 - mae: 6411.3306
Epoch 121/200
34/34 [==============================] - 0s 3ms/step - loss: 6406.1289 - mae: 6406.1289
Epoch 122/200
34/34 [==============================] - 0s 2ms/step - loss: 6401.0415 - mae: 6401.0415
Epoch 123/200
34/34 [==============================] - 0s 3ms/step - loss: 6395.3340 - mae: 6395.3340
Epoch 124/200
34/34 [==============================] - 0s 3ms/step - loss: 6389.6133 - mae: 6389.6133
Epoch 125/200
34/34 [==============================] - 0s 3ms/step - loss: 6385.0015 - mae: 6385.0015
Epoch 126/200
34/34 [==============================] - 0s 3ms/step - loss: 6378.0757 - mae: 6378.0757
Epoch 127/200
34/34 [==============================] - 0s 3ms/step - loss: 6373.0596 - mae: 6373.0596
Epoch 128/200
34/34 [==============================] - 0s 3ms/step - loss: 6367.6104 - mae: 6367.6104
Epoch 129/200
34/34 [==============================] - 0s 3ms/step - loss: 6361.6309 - mae: 6361.6309
Epoch 130/200
34/34 [==============================] - 0s 3ms/step - loss: 6356.5308 - mae: 6356.5308
Epoch 131/200
34/34 [==============================] - 0s 2ms/step - loss: 6351.8555 - mae: 6351.8555
Epoch 132/200
34/34 [==============================] - 0s 2ms/step - loss: 6348.3027 - mae: 6348.3027
Epoch 133/200
34/34 [==============================] - 0s 2ms/step - loss: 6340.0728 - mae: 6340.0728
Epoch 134/200
34/34 [==============================] - 0s 2ms/step - loss: 6334.4619 - mae: 6334.4619
Epoch 135/200
34/34 [==============================] - 0s 3ms/step - loss: 6328.7476 - mae: 6328.7476
Epoch 136/200
34/34 [==============================] - 0s 3ms/step - loss: 6322.4326 - mae: 6322.4326
Epoch 137/200
34/34 [==============================] - 0s 3ms/step - loss: 6316.6494 - mae: 6316.6494
Epoch 138/200
34/34 [==============================] - 0s 3ms/step - loss: 6310.2197 - mae: 6310.2197
Epoch 139/200
34/34 [==============================] - 0s 2ms/step - loss: 6305.2217 - mae: 6305.2217
Epoch 140/200
34/34 [==============================] - 0s 2ms/step - loss: 6299.3003 - mae: 6299.3003
Epoch 141/200
34/34 [==============================] - 0s 2ms/step - loss: 6293.6831 - mae: 6293.6831
Epoch 142/200
34/34 [==============================] - 0s 3ms/step - loss: 6287.1353 - mae: 6287.1353
Epoch 143/200
34/34 [==============================] - 0s 3ms/step - loss: 6285.2422 - mae: 6285.2422
Epoch 144/200
34/34 [==============================] - 0s 2ms/step - loss: 6276.9263 - mae: 6276.9263
Epoch 145/200
34/34 [==============================] - 0s 2ms/step - loss: 6269.2798 - mae: 6269.2798
Epoch 146/200
34/34 [==============================] - 0s 2ms/step - loss: 6263.5762 - mae: 6263.5762
Epoch 147/200
34/34 [==============================] - 0s 2ms/step - loss: 6258.0049 - mae: 6258.0049
Epoch 148/200
34/34 [==============================] - 0s 2ms/step - loss: 6250.9707 - mae: 6250.9707
Epoch 149/200
34/34 [==============================] - 0s 2ms/step - loss: 6243.4116 - mae: 6243.4116
Epoch 150/200
34/34 [==============================] - 0s 2ms/step - loss: 6238.8184 - mae: 6238.8184
Epoch 151/200
34/34 [==============================] - 0s 2ms/step - loss: 6232.7568 - mae: 6232.7568
Epoch 152/200
34/34 [==============================] - 0s 2ms/step - loss: 6224.6924 - mae: 6224.6924
Epoch 153/200
34/34 [==============================] - 0s 2ms/step - loss: 6220.6206 - mae: 6220.6206
Epoch 154/200
34/34 [==============================] - 0s 2ms/step - loss: 6212.4971 - mae: 6212.4971
Epoch 155/200
34/34 [==============================] - 0s 2ms/step - loss: 6205.3643 - mae: 6205.3643
Epoch 156/200
34/34 [==============================] - 0s 2ms/step - loss: 6197.2612 - mae: 6197.2612
Epoch 157/200
34/34 [==============================] - 0s 2ms/step - loss: 6190.7427 - mae: 6190.7427
Epoch 158/200
34/34 [==============================] - 0s 2ms/step - loss: 6183.4922 - mae: 6183.4922
Epoch 159/200
34/34 [==============================] - 0s 2ms/step - loss: 6176.3926 - mae: 6176.3926
Epoch 160/200
34/34 [==============================] - 0s 2ms/step - loss: 6169.9453 - mae: 6169.9453
Epoch 161/200
34/34 [==============================] - 0s 2ms/step - loss: 6163.2051 - mae: 6163.2051
Epoch 162/200
34/34 [==============================] - 0s 2ms/step - loss: 6155.4097 - mae: 6155.4097
Epoch 163/200
34/34 [==============================] - 0s 2ms/step - loss: 6147.4668 - mae: 6147.4668
Epoch 164/200
34/34 [==============================] - 0s 2ms/step - loss: 6140.5020 - mae: 6140.5020
Epoch 165/200
34/34 [==============================] - 0s 2ms/step - loss: 6134.4429 - mae: 6134.4429
Epoch 166/200
34/34 [==============================] - 0s 2ms/step - loss: 6124.8657 - mae: 6124.8657
Epoch 167/200
34/34 [==============================] - 0s 2ms/step - loss: 6117.9707 - mae: 6117.9707
Epoch 168/200
34/34 [==============================] - 0s 2ms/step - loss: 6111.3682 - mae: 6111.3682
Epoch 169/200
34/34 [==============================] - 0s 2ms/step - loss: 6105.7021 - mae: 6105.7021
Epoch 170/200
34/34 [==============================] - 0s 2ms/step - loss: 6094.7119 - mae: 6094.7119
Epoch 171/200
34/34 [==============================] - 0s 2ms/step - loss: 6087.4492 - mae: 6087.4492
Epoch 172/200
34/34 [==============================] - 0s 2ms/step - loss: 6078.6348 - mae: 6078.6348
Epoch 173/200
34/34 [==============================] - 0s 2ms/step - loss: 6071.1812 - mae: 6071.1812
Epoch 174/200
34/34 [==============================] - 0s 2ms/step - loss: 6062.4800 - mae: 6062.4800
Epoch 175/200
34/34 [==============================] - 0s 2ms/step - loss: 6054.7715 - mae: 6054.7715
Epoch 176/200
34/34 [==============================] - 0s 2ms/step - loss: 6045.6338 - mae: 6045.6338
Epoch 177/200
34/34 [==============================] - 0s 2ms/step - loss: 6035.8730 - mae: 6035.8730
Epoch 178/200
34/34 [==============================] - 0s 2ms/step - loss: 6027.2856 - mae: 6027.2856
Epoch 179/200
34/34 [==============================] - 0s 2ms/step - loss: 6019.0684 - mae: 6019.0684
Epoch 180/200
34/34 [==============================] - 0s 2ms/step - loss: 6011.1348 - mae: 6011.1348
Epoch 181/200
34/34 [==============================] - 0s 2ms/step - loss: 6001.9404 - mae: 6001.9404
Epoch 182/200
34/34 [==============================] - 0s 2ms/step - loss: 5990.3027 - mae: 5990.3027
Epoch 183/200
34/34 [==============================] - 0s 2ms/step - loss: 5981.5093 - mae: 5981.5093
Epoch 184/200
34/34 [==============================] - 0s 2ms/step - loss: 5973.9565 - mae: 5973.9565
Epoch 185/200
34/34 [==============================] - 0s 2ms/step - loss: 5962.6841 - mae: 5962.6841
Epoch 186/200
34/34 [==============================] - 0s 2ms/step - loss: 5951.9126 - mae: 5951.9126
Epoch 187/200
34/34 [==============================] - 0s 2ms/step - loss: 5941.8643 - mae: 5941.8643
Epoch 188/200
34/34 [==============================] - 0s 2ms/step - loss: 5931.2090 - mae: 5931.2090
Epoch 189/200
34/34 [==============================] - 0s 2ms/step - loss: 5920.9678 - mae: 5920.9678
Epoch 190/200
34/34 [==============================] - 0s 2ms/step - loss: 5913.6650 - mae: 5913.6650
Epoch 191/200
34/34 [==============================] - 0s 2ms/step - loss: 5899.8750 - mae: 5899.8750
Epoch 192/200
34/34 [==============================] - 0s 2ms/step - loss: 5888.0469 - mae: 5888.0469
Epoch 193/200
34/34 [==============================] - 0s 2ms/step - loss: 5880.1743 - mae: 5880.1743
Epoch 194/200
34/34 [==============================] - 0s 2ms/step - loss: 5866.0747 - mae: 5866.0747
Epoch 195/200
34/34 [==============================] - 0s 2ms/step - loss: 5854.2002 - mae: 5854.2002
Epoch 196/200
34/34 [==============================] - 0s 2ms/step - loss: 5842.6372 - mae: 5842.6372
Epoch 197/200

In [12]:
# Let's evaluate our model
model.evaluate(X_test, y_test)

9/9 [==============================] - 0s 2ms/step - loss: 5651.2109 - mae: 5651.2109

[5651.2109375, 5651.2109375]

Seems like our model is improving